apiVersion: v1
kind: Service
metadata:
  labels:
    app: llamas
  name: llamas
  namespace: llamas-blue
spec:
  ports:
  - nodePort: 31104
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: llamas
  type: NodePort
