apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: llamas
  name: llamas
  namespace: llamas-blue
spec:
  selector:
    matchLabels:
      app: llamas
  strategy:
    blueGreen:
      activeService: llamas
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: llamas
    spec:
      containers:
      - image: bldr0cuomrepo1.dev.internal.pri:5000/llamas:v1.2
        imagePullPolicy: Always
        name: llamas
        resources:
          limits:
            cpu: "40m"
            memory: "30Mi"
          requests:
            cpu: "30m"
            memory: "20Mi"
      priorityClassName: business-essential

