apiVersion: v1
kind: Service
metadata:
  labels:
    app: llamas
  name: llamas
  namespace: llamas-green
spec:
  ports:
  - nodePort: 32102
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: llamas
  type: NodePort
