apiVersion: v1
kind: LimitRange
metadata:
  name: llamas-lr
  namespace: llamas
spec:
  limits:
  - default:
      memory: 10Mi
      cpu: 30m
    defaultRequest:
      memory: 30Mi
      cpu: 90m
    type: Container
