apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llamas-stage
  namespace: argocd
spec:
  project: llamas-green
  source:
    repoURL: git@lnmt1cuomgitlab.internal.pri/external-unix/gitops.git
    targetRevision: main
    path: stage/llamas-green/
    directory:
      recurse: true
  destination:
    server: https://tato0cuomvip1.stage.internal.pri:6443
    namespace: llamas-green
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: llamas
      namespace: llamas-green
      jqPathExpressions:
        - .spec.template.spec.replicas

