apiVersion: v1
kind: LimitRange
metadata:
  name: llamas-lr
  namespace: llamas-green
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 512m
    defaultRequest:
      memory: 128Mi
      cpu: 128m
    type: Container
